filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/wallet-service/service.log
- type: log
  enabled: true
  paths:
    - /var/log/wallet-web/service.log
- type: log
  enabled: true
  paths:
    - /var/log/pai-web/service.log

setup.template.settings:
  index.number_of_shards: 3

output.elasticsearch:
  hosts: ["http://172.16.219.237:21092"]

setup.kibana:
  host: "http://172.16.219.237:8601"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

